# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olxapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='viewcount',
            field=models.IntegerField(default=0),
        ),
    ]
