# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olxapp', '0002_auto_20170921_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='phoneno',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
